### ISSUE TITLE
Remove deprecate field replicas from eventlistener spec

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#1020]
`Replicas` are deprecated from Eventlistener Spec and added as part of `resources.kubernetesResource`.
deprecated replicas will be removed in a future release.

**Comment by coyote240** [comment]
EventListeners are behaving as though this were already removed instead of deprecated:

`error: eventlisteners.triggers.tekton.dev "redacted" could not be patched: admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "replicas"`

**Comment by savitaashture** [comment]
@coyote240 are you facing this with latest code ?

**Comment by sm43** [comment]
Done in #1113 
/close
