### ISSUE TITLE
Can't install binding-eval tool due to Google's namespace change on github

### ISSUE THREAD

**Issue by pascalgulikers** [tektoncd/triggers#1279]
# Expected Behavior
Installation of binding-eval tool
# Actual Behavior
go get -u github.com/tektoncd/triggers/cmd/binding-eval
go get: github.com/googleapis/gnostic@v0.5.7: parsing go.mod:
        module declares its path as: github.com/google/gnostic
                but was required as: github.com/googleapis/gnostic
# Steps to Reproduce the Problem

1.  go get -u github.com/tektoncd/triggers/cmd/binding-eval
2.
3.

# Additional Info

**Comment by wlynch** [comment]
This is unfortunately a problem with Go package version resolution that's upstream to us. :( See https://github.com/google/gnostic/issues/262.

When you pass the `-u` flag, that's instructing Go to pull recent minor/patch module updates. Since the gnostic module rename happened in 0.5.6 -> 0.5.7  it's pulled in and causes breakages because it's a patch version.

As an alternative, try using `go get github.com/tektoncd/triggers/cmd/binding-eval` instead.

Created #1281 which will hopefully let you use `go install <pkg>@latest` as an alternative (since as of Go 1.17 there's a warning about using `go get` for binary installation).

**Comment by pascalgulikers** [comment]
go get github.com/tektoncd/triggers/cmd/binding-eval 
gives:

```
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go get: installing executables with 'go get' in module mode is deprecated.
        To adjust and download dependencies of the current module, use 'go get -d'.
        To install using requirements of the current module, use 'go install'.
        To install ignoring the current module, use 'go install' with a version,
        like 'go install example.com/cmd@latest'.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```
indeed :(
