### ISSUE TITLE
Create getting started guide

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#13]
## Expected behavior

People who want to use Triggers should have an obvious place to look for some quick start docs on how they can get up and running, e.g.:

- How to install and setup
- What the types are and how to use them
- Where to look for more

## Actual behavior

In #2 we'll add a DEVELOPMENT.md for contributors, but we won't have any getting started docs for users.

## Additional info

May want to use https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md as an example.

**Comment by vtereso** [comment]
It seem like this is mostly done? The installation (since we currently have no release) is specified in the DEVELOPMENT.md. To my understanding, the other two points seem to be sufficient as well. Maybe additionally link/add this https://github.com/tektoncd/triggers/blob/master/DEVELOPMENT.md#install-triggers to the top level README?

**Comment by EliZucker** [comment]
I'll look at finishing this up. /assign

**Comment by EliZucker** [comment]
nvm just saw you assigned yourself..

**Comment by vtereso** [comment]
Not sure how to proceed with this for now.
/unassign

**Comment by akihikokuroda** [comment]
@iancoffey I wonder if the getting start doc is the good place to put the reference to the create Webhooks doc?
https://github.com/tektoncd/triggers/pull/82#pullrequestreview-281061107

**Comment by iancoffey** [comment]
@akihikokuroda Yes, this sounds like a good place to me! 

I had been waiting for https://github.com/tektoncd/triggers/pull/74 to land before beginning this guide but an install guide sounds like a nice start.

**Comment by bobcatfish** [comment]
@iancoffey we've got #74 now!! :tada: :tada: :tada:

**Comment by iancoffey** [comment]
Pardon the delay on this! I have a good start here and should push something for yall to validate this coming week.

**Comment by iancoffey** [comment]
I have opened an early WIP pr here and should have the branch done this week -> https://github.com/tektoncd/triggers/pull/135

Since there are several good documents in this repo already, the idea behind this guide is to focus on making sure an operators first real Triggers project starts off well by building a real system. It will use the webhook task and highlight the RBAC aspect of the triggers a bit too, when complete.

**Comment by ncskier** [comment]
#135 is merged, so closing this issue.
