### ISSUE TITLE
EventListner service name is a generatedName

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/triggers#145]
# Expected Behavior

Event listener service name should be the name of the event listener so that it can be addressed easily in the cluster. 

# Actual Behavior

The event listener name has been changed to the generatedName.  It can be obtained from the status of the event listener resource but it is not necessary to be the generatedName.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by vtereso** [comment]
I made this change since the reconciler currently reconciles the service and deployment state against the `EventListener` name. If there was already a service/deployment existent with the same name as the `EventListener`, we would rewrite its defintion.

**Comment by akihikokuroda** [comment]
I think it should be overwritten.  If the EventListner service with the same name  as the EventListener exists, it's like a phushing

**Comment by vtereso** [comment]
@dibyom @ncskier Thoughts? I know it makes things slightly more cumbersome, but I also don't think it's too bad to get the service name (done [here](https://github.com/tektoncd/triggers/blob/master/test/e2e-tests-ingress.sh#L71)). When we pull the service name from the `EventListener` status, we can be certain that is up. I feel that collisions could occur if someone had an application and they used the same name in their `EventListener`.

**Comment by dibyom** [comment]
Could go either way on this one. I think the status should be the definitive place that contains the deployment/service instead of us relying on conventions. 

How common is the collision case of an existing deployment/service having ? Instead of overwriting, can we just return an error and refuse to create the service/deployment?

**Comment by dibyom** [comment]
FWIW, this pattern exists elsewhere...when I create a new GithubSource (e.g. the githubsource-sample) , the deployment that gets created seems to be a generated name: ` githubsourcesample-46hb2-xn4dn-deployment`. The service name is: `githubsourcesample-46hb2-xn4dn`

**Comment by akihikokuroda** [comment]
If this is the design, the creation of the ingress and the webhook become complicated.  It must wait until the event listener service is created.   The create ingress and webhook docs must be changed.

**Comment by akihikokuroda** [comment]
The issue is the service name.  The service name is a name used to refer to the service.  It must be well known name.

**Comment by dibyom** [comment]
In the getting started PR at least, the event listener gets created first and then the ingress/webhook. If that is the flow we recommend, the webhook/ingress task can take the EventListener name as input as figure out the service name from the el Status?

> The issue is the service name. The service name is a name used to refer to the service. It must be well known name.

Yeah, I guess I think this comes back to what is the API that the event listener exposes. The service name seems to be part of the API; whether or not it is a generated or the same name as the event listener, it should be available via a field in the Status instead of being a convention

**Comment by dibyom** [comment]
Ok, I think I understand the Ingress problem. If you create and recreate the event listener now, you will also have to rerun the ingress task since the service name is not deterministic anymore. Is that accurate @akihikokuroda ?

**Comment by akihikokuroda** [comment]
Yes, that's a part of issue.  It annoys the user :-)   I like the prefix idea.  It makes less conflicts and easy to understand for the user.
