### ISSUE TITLE
Interceptor fails to get secrets which lead to unrecoverable eventlistener failures

### ISSUE THREAD

**Issue by jwitrick** [tektoncd/triggers#1478]
Since upgrading to tekton triggers: 0.21 we have noticed our eventlisteners would suddenly stop working and the error logs would be filled with:
```
{"level":"error","ts":"2022-11-03T11:49:19.299Z","logger":"eventlistener","caller":"sink/sink.go:381","msg":"Post \"https://tekton-triggers-core-interceptors.tekton-pipelines.svc:8443/cel\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"tekton-triggers-core-interceptors.tekton-pipelines.svc\")","eventlistener":"mylistener","namespace":"app-prod","/triggers-eventid":"20b3c97f-90e2-4f85-8fa9-05dffc7259a9","eventlistenerUID":"07ef4762-72d6-4e0f-8813-7bd84ca49d07","/triggers-eventid":"20b3c97f-90e2-4f85-8fa9-05dffc7259a9","/trigger":"rake-task","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:381\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196"}
``` 
And the errors will continue to happen until the Eventlistener pod is killed. 

After looking around I noticed at the same time the eventlistener starts having errors there are logs in the core-interceptor pod:

```
{"level":"info","ts":1667570794.8050323,"caller":"server/server.go:150","msg":"Interceptor response is: &{Extensions:map[] Continue:true Status:{Code:OK Message:}}"}
{"level":"info","ts":1667570867.9983332,"caller":"server/server.go:150","msg":"Interceptor response is: &{Extensions:map[] Continue:false Status:{Code:FailedPrecondition Message:expression has(body.task) did not return true}}"}
{"level":"info","ts":1667570867.998569,"caller":"server/server.go:150","msg":"Interceptor response is: &{Extensions:map[] Continue:true Status:{Code:OK Message:}}"}
{"level":"info","ts":1667570891.6357741,"caller":"server/server.go:150","msg":"Interceptor response is: &{Extensions:map[] Continue:false Status:{Code:FailedPrecondition Message:expression has(body.task) did not return true}}"}
{"level":"info","ts":1667521790.5477786,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
W1104 00:30:20.548510       1 reflector.go:324] runtime/asm_amd64.s:1571: failed to list *v1.Secret: Get "[https://172.20.0.1:443/api/v1/secrets?limit=500&resourceVersion=0](https://172.20.0.1/api/v1/secrets?limit=500&resourceVersion=0)": dial tcp 172.20.0.1:443: i/o timeout
I1104 00:30:20.548708       1 trace.go:205] Trace[1298498081]: "Reflector ListAndWatch" name:runtime/asm_amd64.s:1571 (04-Nov-2022 00:29:50.547) (total time: 30000ms):
Trace[1298498081]: ---"Objects listed" error:Get "[https://172.20.0.1:443/api/v1/secrets?limit=500&resourceVersion=0](https://172.20.0.1/api/v1/secrets?limit=500&resourceVersion=0)": dial tcp 172.20.0.1:443: i/o timeout 30000ms (00:30:20.548)
Trace[1298498081]: [30.000783773s] [30.000783773s] END
E1104 00:30:20.548730       1 reflector.go:138] runtime/asm_amd64.s:1571: Failed to watch *v1.Secret: failed to list *v1.Secret: Get "[https://172.20.0.1:443/api/v1/secrets?limit=500&resourceVersion=0](https://172.20.0.1/api/v1/secrets?limit=500&resourceVersion=0)": dial tcp 172.20.0.1:443: i/o timeout
{"level":"info","ts":1667521823.7331553,"caller":"interceptors/main.go:178","msg":"Listen and serve on port 8443"}
2022/11/04 00:35:27 http: TLS handshake error from 10.40.62.237:35114: remote error: tls: bad certificate
```

# Expected Behavior

Ideally it should not timeout.. but if it does then when its able to list/verify things again the eventlisteners should re-connect correctly ... OR the eventlistener should become unhealthy which would allow for it to be automatically killed and new eventlistener pod to start.

# Actual Behavior

The eventlistener is never able to re-connect and will always throw the error: `x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate` over and over again (for hours) untili the eventlistener pod is manually killed.

# Steps to Reproduce the Problem

No idea how to re-produce it.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.27.0
Pipeline version: v0.40.2
Triggers version: v0.21.0
Dashboard version: v0.29.2
```

We are running in AWS EKS. We have been using Tekton for ~2 years and have never seen the eventlistener behave in this manor before.

**Comment by dibyom** [comment]
> Ideally it should not timeout.. but if it does then when its able to list/verify things again the eventlisteners should re-connect correctly ... OR the eventlistener should become unhealthy which would allow for it to be automatically killed and new eventlistener pod to start.

Makes sense to me.

@savitaashture any idea why the certs would go bad? Shouldn't the expiry time for them be fairly long?

**Comment by treyhyde** [comment]
Since rolling back to 0.20.x I can confirm we haven't seen this.   Probably directly related to https://github.com/tektoncd/triggers/pull/1385.

0.21.x was pretty catastrophic for us.

Any idea why there are certificates at all in this path?

**Comment by savitaashture** [comment]
> Since rolling back to 0.20.x I can confirm we haven't seen this. Probably directly related to #1385.
> 
> 0.21.x was pretty catastrophic for us.
> 
> Any idea why there are certificates at all in this path?

Hi @treyhyde 
could you provide the steps to reproduce issue
Because for me upgrade is working fine

**Comment by treyhyde** [comment]
I don't know if we have a silver bullet for reproduction.  

The EventListeners in question as configured as Ksvc (Knative Service) as per the example here: https://tekton.dev/docs/triggers/eventlisteners/#contract-for-the-customresource-object.   

We have a few ELs in this namespace but the one that triggered this frequently was the one that was least likely to scale to 0 and live for many hours.  The above problem seemed to manifest right around midnight UTC every day after 0.21.x rolled out.

I'm still trying to figure out what these certs are for.  If this is for simple TLS than of course we'd want them gone as that is better off in the network layer than the application layer and really hampers observability and overall security.  Again, if so, I would really love an option to disable the TLS at the application layer or at the least return the behavior to "no-verify" and/or "no-rotate".

**Comment by treyhyde** [comment]
```
    Manager:      Go-http-client
    Operation:    Update
    Subresource:  status
    Time:         2022-08-04T22:16:31Z
    API Version:  triggers.tekton.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:clientConfig:
          f:caBundle:
```

Does this mean this was the last time the cabundle was updated?

In reviewing the 0.21.x change, I noticed there is a lot of polling, sometimes with only 10s wait.  Kube API is too slow overall, I wonder if a single slow API call could cause this to fail in unexpected ways.

**Comment by savitaashture** [comment]
Hi @treyhyde I tried below steps

**Comment by krishnaraman001** [comment]
Hi all,
I am also getting the same exception
`{"level":"error","ts":"2022-11-22T06:44:45.487Z","logger":"eventlistener","caller":"sink/sink.go:381","msg":"Post \"https://tekton-triggers-core-interceptors.tekton-pipelines.svc:8443/cel\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"tekton-triggers-core-interceptors.tekton-pipelines.svc\")","eventlistener":"bitbucket-pr","namespace":"pie-servicehub-dev","/triggers-eventid":"79d5a20c-5603-4c5e-8169-fe5cc20f5961","eventlistenerUID":"bb2cb4bf-fc62-45dd-aa2f-957b446e7c76","/triggers-eventid":"79d5a20c-5603-4c5e-8169-fe5cc20f5961","/trigger":"pie-servicehub-knightly-listener","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:381\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196"}`


EKS CLUSTER: EKS 1.23
Pipelines: v0.38.3
Triggers: v0.20.2 
Dashboard: v0.28.0

**Comment by jwitrick** [comment]
#

> Hi @treyhyde I tried below steps
> 
> 1. Install [v0.19.1](https://github.com/tektoncd/triggers/releases/tag/v0.19.1) where ClusterInterceptor don't have `caBundle`
> 2. Created EL
> 3. Sent Few requests and got success response
> 4. Upgraded Triggers to 0.21 where ClusterInterceptor have `caBundle`
> 5. EL came up successfully without any error and able to server request
> 
> Let me know do you see errors still

@savitaashture have you looked back at your setup after 1, 2, 3, etcc.. days and confirmed you dont see the issues? Also how many events are being sent to the EL, and how busy if your cluster?

When we were having this issue, it was occurring every ~24 hours and it was difficult for us to detect..besides watching logs.

**Comment by krishnaraman001** [comment]
`{"level":"error","ts":"2022-11-22T06:44:45.487Z","logger":"eventlistener","caller":"sink/sink.go:381","msg":"Post \"https://tekton-triggers-core-interceptors.tekton-pipelines.svc:8443/cel\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"tekton-triggers-core-interceptors.tekton-pipelines.svc\")","eventlistener":"bitbucket-pr","namespace":"pie-servicehub-dev","/triggers-eventid":"79d5a20c-5603-4c5e-8169-fe5cc20f5961","eventlistenerUID":"bb2cb4bf-fc62-45dd-aa2f-957b446e7c76","/triggers-eventid":"79d5a20c-5603-4c5e-8169-fe5cc20f5961","/trigger":"pie-servicehub-knightly-listener","stacktrace":"[github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger](http://github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger)\n\[tgithub.com/tektoncd/triggers/pkg/sink/sink.go:381](http://tgithub.com/tektoncd/triggers/pkg/sink/sink.go:381)\[ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1](http://ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1)\n\[tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196](http://tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196)"}`

@savitaashture  the above issue frequently happens to us when we add interceptors inside the trigger manifest, but when we remove those interceptors it works fine.

```
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: bitbucket-listener
spec:
  interceptors:
    - ref:
        name: "bitbucket"
      params:
        - name: "eventTypes"
          value:
            - pullrequest:fulfilled
            - repo:push
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "(header.match('X-Event-Key', 'repo:push') ? body.push.changes[0].new.name in ['master'] : body.pull_request.destination.branch.name in ['master'])" 
        - name: "overlays"
          value:
            - key: truncated_sha
              expression: "header.match('X-Event-Key', 'repo:push') ? body.push.changes[0].new.target.hash.truncate(7) : body.pull_request.merge_commit.truncate(7)"    
  bindings:
    - ref: bitbucket-pr-binding
  template:
    ref: ci-trigger-template
```

**Comment by savitaashture** [comment]
> > Hi @treyhyde I tried below steps
> > 
> > 1. Install [v0.19.1](https://github.com/tektoncd/triggers/releases/tag/v0.19.1) where ClusterInterceptor don't have `caBundle`
> > 2. Created EL
> > 3. Sent Few requests and got success response
> > 4. Upgraded Triggers to 0.21 where ClusterInterceptor have `caBundle`
> > 5. EL came up successfully without any error and able to server request
> > 
> > Let me know do you see errors still
> 
> @savitaashture have you looked back at your setup after 1, 2, 3, etcc.. days and confirmed you dont see the issues? Also how many events are being sent to the EL, and how busy if your cluster?
> 
> When we were having this issue, it was occurring every ~24 hours and it was difficult for us to detect..besides watching logs.

Hi @jwitrick 

I have not kept setup for 3-4 days and it was not that busy

May be need to stress testing and then need to check the failure reason but i am confused here that we generated token which expiration time is too long but how those errors are seen :thinking: 

Is that because of http request throttling  :thinking:

**Comment by savitaashture** [comment]
Will try with making system busy by sending request continuously using loop 
Lets see how it behaves

**Comment by jwitrick** [comment]
My comment didnt take.

After upgrading to Triggers v0.22.2 and letting it run for ~6 days this issue has not re-occurred. As we could not reliably replicate outside of our production environment and with the upgrade the issue is not happening. I am closing this issue.
