### ISSUE TITLE
Support JSONPath syntax for variable extraction in TriggerBindings

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#178]
# Expected Behavior
A user should _intuitively_ be able to specify a [`body`](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md#body) parameter to point to a piece of data in their HTTP request JSON body. 

# Actual Behavior
Currently, the Triggers project is using the [gjson](https://github.com/tidwall/gjson) library because it makes it easy for us to search the JSON for a specified path. However, gjson does not use the conventional JSONPath syntax, instead it has its own [GJSON path syntax](https://github.com/tidwall/gjson/blob/master/SYNTAX.md). Since the gjson path syntax is different from the JSONPath syntax, it can be unintuitive, and Triggers does not have any documentation linking to an explanation of this syntax.

Furthermore, the [`bodyPathVarRegex`](https://github.com/tektoncd/triggers/blob/master/pkg/template/event.go#L30) limits the user to a subset of the gjson syntax.

# Additional Info
This concern originated in our Slack channel [here](https://tektoncd.slack.com/archives/CKUSJ2A5D/p1571198034014600).

### I hope that the following work will come from this issue:
Decide whether to keep the gjson path syntax, or switch to JSONPath
1. If we decide to keep the gjson library and the gjson path syntax
- add Triggers documentation linking to the gjson path syntax page
- update the `bodyPathVarRegex` to accept all valid gjson path syntax
- update/add tests for examples using gjson path syntax
2. If we decide to use JSONPath syntax
- find a library that we can substitute for gjson (or use with gjson?)
- update code & tests to use the JSONPath syntax
- add Triggers documentation linking to an explanation of the JSONPath syntax

**Comment by dibyom** [comment]
JSONPath definitely seems more popular and is definitely used in other parts of k8s (e.g. kubectl supports it)

**Comment by kav** [comment]
My inclination as a user would be to match standard json syntax  _unless_
1. The expressiveness of the querying capabilities is an important feature here and throughout Tekton (or even just Triggers)
1. gjson is standard elsewhere in the Kubernetes or even Tekton ecosystem 

Those are true perhaps updating the regex to catch `[` and `]` and report to the user that they might want to read about gjson.

I could definitely see 1 being the case if gjson was also being used to add a lightweight filter property to the event listener but it doesn't look to have boolean operations built in. JSONPath on the other hand seems like it might fit the bill there... Not to derail into a feature pitch. Not sure what the Go libraries look like either.

**Comment by ncskier** [comment]
From some quick searching, I didn't find any JSONPath Go libraries with a lot of support.

The one that seemed to fit and had the most stars was https://github.com/oliveagle/jsonpath, but it says `this library is till bleeding edge, so use it at your own risk. :D` (which is a typo) 😅 

https://github.com/buger/jsonparser seems to be more popular, and does not require us to know the structure of the payload (similar to gjson), but I don't think it strictly supports JSONPath syntax.

Does anyone know if Kubernetes uses a library or has their own library that we could use?

**Comment by akihikokuroda** [comment]
I like the JSONPath better.  Can we add a flag for the syntax and support multiple libraries?

**Comment by ncskier** [comment]
I think it'd be best to stick to one syntax (and one library) to avoid confusion & more convoluted code.

From the discussion here, it sounds like JSONPath would be best for us to use. It seems like whoever picks up this issue to implement JSONPath should probably check out the https://godoc.org/k8s.io/client-go/util/jsonpath library that @dibyom mentioned, or find another library to replace the gjson library in our Triggers code 👍

**Comment by wlynch** [comment]
Alternative to consider: [CEL](https://github.com/google/cel-spec)

This is what [Knative plans to use for its conditionals](https://github.com/knative/eventing/blob/master/docs/broker/filtering.md), and I think this would be useful to use for interpolation as well. See https://github.com/google/cel-spec/blob/master/doc/langdef.md for the full spec.

See https://github.com/google/cel-go for Go implementation.

This may be a better syntax for not just expressing field extraction, but also expressing logical operations over gjson. For example we can specify expressions such as `has(field)? field : "defaultvalue"` for inline defaults, or allow more complex logic for arbitrary evaluation.

Other benefits include supporting Protobuf out of the box, which may be important if we want EventListeners to support gRPC in the future.

**Comment by bobcatfish** [comment]
My 2 cents (apologies to everyone who already has to hear me say this all the time):

An important requirement here imo is that no matter what we provide, someone is always going to have a use case where they want to do something more complicated. Once they want to do that more complicated thing, there's a good chance they're going to want to do it in the language / syntax of their choice. If we don't make that possible, we undermine one of the goals of the tekton components, which is to be flexible enough that we can reduce fragmentation in the CI/CD ecosystem (i.e. if we don't support the syntax/functionality that user X wants, user X will have to either 1) deal with it, 2) use something else 3) make their own thing).

I think whatever we choose, it's gotta be possible for a user to provide their own thing. Containers are a natural extension point for this (e.g. #49 ) but since we sometimes want to avoid spinning up resources for evaluation (like in an interceptor that decides if a request is valid) that doesn't always work and it seems like we need a sane default.

So one way of going forward would be:
- For our default, pick something we think is simple and relatively widely accepted (maybe json path?)
- I think we should have another way of providing data into a trigger binding that is dynamic (https://github.com/tektoncd/triggers/issues/87), which could be a way to support something like CEL. As far as I can tell CEL actually provides a lot more power (like @wlynch has made a POC where you can have CEL actually make a request to github to get more information using a custom library you extend CEL with -> supporting extending CEL with a customer library I'm guessing is something that would be very hard to express within the context of a trigger binding?). If we allow that, we could even out of the box provide some kinda predefined types that know how to provide data using something like CEL, or whatever else, and let users bring their own types too.

**Comment by bobcatfish** [comment]
A couple other principles I want to throw in here:

1. Being very deliberate with our interfaces
2. Keeping coupling and dependencies on other projects to an absolute minimum

The coupling one is interesting: in both pipelines and trigers we depend on a lot of projects in our source, we don't actually run instances of other services. This question might feel like "oh it's not a dependency because we don't expect users to run and maintain another service" but it does mean that _our interface_ becomes dependent on an external project.

Anyway I'll butt out of the discussion now; imo we should choose jsonpath (the most popular and well known option afaik) and later add support for CEL (and other languages as well).

**Comment by dibyom** [comment]
Based on the WG discussion today, we agreed to move forward with replacing Gjson with JSONPath for event variable interpolation in trigger bindings.

**Comment by dibyom** [comment]
Played around with https://godoc.org/k8s.io/client-go/util/jsonpath a bit. Seems relatively simple to use: https://gist.github.com/dibyom/cbc8fa7cf0890dcac3b02817a5c326d3#file-main-go

One decision to make is whether to combine Tekton's variable interpolation syntax aka the `$()` with the JSONPath syntax of the form `{.head_commit.id}`. 

When combined it looks like this: `$({.head_commit.id})` -- which seems ugly and error prone.

Kubectl supports a  [`RelaxedJSONPathExpression`](https://godoc.org/github.com/kubernetes/kubectl/pkg/cmd/get#RelaxedJSONPathExpression) which supports: 
 ```
  * metadata.name (no leading '.' or curly braces '{...}'
  * {metadata.name} (no leading '.')
  * .metadata.name (no curly braces '{...}')
  * {.metadata.name} (complete expression)
  ```
So, another option is something like `$(head_commit.id)` which is simpler and consistent with kubectl syntax though might be a bit confusing.

Finally, a third option is to not use our `$()` syntax at all and only use JSONPath (consistent with k8s but not with the rest of the tekton variable syntax):
```
spec:
  params:
  - name: gitrevision
    value: body.head_commit.id
  - name: gitrepositoryurl
    value: {.body.repository.url}
```

I'm leaning towards the second syntax of keeping the tekton `$()` and using a relaxedJSONPathExpression

**Comment by vtereso** [comment]
Definitely option 2 or 3. I don't particularly like curly braces because it looks like a template, but it isn't? To keep consistency with stuff like `$(uid)`, I suppose I vote option 2.

**Comment by wlynch** [comment]
How do we distinguish JSONPath from raw strings? e.g. the JSONPath filter body.head_commit.id vs the raw value "body.head_commit.id"?

Should we always enforce the use of `{}`?

**Comment by dibyom** [comment]
Good question. What I'm thinking (using Option 2 from above) is using the `$()` to differentiate. So, a user would do the following:
* `$(body.head_commit.id)` - JSONPath value replaced
* `body.head_commit.id` - raw string.
