### ISSUE TITLE
Better name for TriggerTemplate?

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#201]
# Expected Behavior

`TriggerTemplate` is a pretty cool idea, which has the potential for being used beyond just in `triggers` b/c folks may have all kinds of circumstances in which they want to create instances of CRDs.

For example in #200 @skaegi is requesting a way to invoke a `TriggerTemplate` without any kind of `EventListener` and [in the PipelineResource redesign](https://docs.google.com/document/d/1euQ_gDTe_dQcVeX4oypODGIQCAkUaMYQH5h7SaeFs44/edit?ts=5dbb44e6#heading=h.7stszktvusgl) I think `TriggerTemplates` could be a cool way to express how to create new instances of `PipelineResources` when created or mutated.

# Actual Behavior

The name `TriggerTemplates` pretty much indicates this is part of triggering, and that's all its good for.

# Additional Info

Some name ideas:

- `ResourceTemplate` <-- cuz we define how to create resources
- `ResourceFactory` <-- ah god the java - but factory isnt a bad name imo!
- `ResourceCreator` <-- i dunno
- `Template` <-- maybe too generic
- `FromParamsToResource` <-- .... okay ill stopp

Also in #200 @skaegi is proposing adding `Run` to the name of whatever this is called, might be interesting to brainstorm what the invocation of this thing could be called also.

p.s. @dibyom @wlynch @vtereso @ncskier @iancoffey if you folks agree with this, renaming before 0.2 could be good

**Comment by vtereso** [comment]
In deciding this, I think we should confirm whether we will or will not be opening templates to create any (or most) kind(s) of resources since that seems significant to the name (e.g. `TektonTemplate` vs `ResourceTemplate`).

Currently templates inject parameters as well as references via the `$(uid)` interpolation variable. In a world where run resources do not reference other event time resources (parameter passing only), the definition/function of a template would still creates Kubernetes resources, but not `PipelineResources`. For this reason, I think including names like `ResourceFactory` could be confusing. This aside, I am mostly indifferent about the naming.

**Comment by dibyom** [comment]
> ResourceTemplate <-- cuz we define how to create resources

Currently, TriggerTemplates contain a field called `ResourceTemplates` containing the raw template

**Comment by dibyom** [comment]
ref #697
