### ISSUE TITLE
Occasional Race-Condition in TriggerTemplate resulting in failed PipelineRun

### ISSUE THREAD

**Issue by ston1th** [tektoncd/triggers#244]
# Expected Behavior
TriggerTemplate gets triggerd and first creates the `PipelineResources` (`git` and `image`) and after these the `PipelineRun`.

# Actual Behavior
Most of the time this works fine but sometimes the `PipelineResources` are not yet fully created at the time the `PipelineRun` wants to start.
This way the `PipelineRun` fails with this error message:

```
PipelineRun tekton-webhook/pipelinerun-f6wwj can't be Run; it tries to bind Resources that don't exist: Error following resource reference for source-repo: pipelineresource.tekton.dev "source-repo-f6wwj" not found
```

# Steps to Reproduce the Problem

Not really reproducable as this happens occasionaly (until now 3 times in total).

# Additional Info
Kubernetes Version: `v1.16.2`
Triggers Version: latest `master`
Pipeline Version: `v0.8.0`

**Comment by dibyom** [comment]
@ston1th I don't think this is a Triggers specific issue. You can run into the same if you create and try to use a pipelineresource and a pipelinerun that uses at the same time. A workaround for this would be to embed the pipeline resource in your pipelinerun instead of creating it as a separate resource: https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#resources

**Comment by ston1th** [comment]
@dibyom Thanks, embedding seems like a good solution to this.
