### ISSUE TITLE
FR: Core Interceptor plugins

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#271]
# Summary

* TEP: https://github.com/tektoncd/community/blob/master/teps/0026-interceptor-plugins.md#work-plan

* Work Plan/Progress: https://github.com/tektoncd/triggers/issues/271#issuecomment-724830692

# Expected Behavior

Core Interceptors should be pluggable so that users can choose which are available by default.

# Actual Behavior

Interceptors are currently static.

# Additional Info

https://github.com/hashicorp/go-plugin is a potential candidate for supporting in-binary plugins.

**Comment by ncskier** [comment]
Waiting for design doc

**Comment by dibyom** [comment]
I wrote up a design proposal: https://docs.google.com/document/d/1zIG295nyWonCXhb8XcOC41q4YVP9o2Hgg8uAoL4NdPA/edit#heading=h.8z1iarlx6yyx

Planning on filing TEP after discussion.

**Comment by dibyom** [comment]
Pending the TEP getting merged, here is the implementation plan:

- [ ]  Migrate core interceptor to new interface structs - We'll migrate the core interceptors to use the new API. In this step, the core interceptors will still run inside the EventListener but will use go structs from the new API. 

- [ ] Implement [TEP-0022](https://github.com/tektoncd/community/pull/218) i.e. modify the CEL interceptor to return extensions instead of modifying the body.

- [ ]  Move the core interceptors to their own deployments - This will involve implementing the core interceptors to their own deployment and using HTTP to communicate. In addition, we will also be adding the InterceptorConfiguration CRD as part of this.

- [ ]  Add TLS support - This will involve adding suport for the `caBundle` field to allow for TLS communication between EventListener and Interceptor.

- [ ] Implement additional features - extra context for debugging, versioning etc.

**Comment by dibyom** [comment]
Shipped in v0.13. Closing.
