### ISSUE TITLE
（GitLab）TriggerBinding.Event Variable Interpolation

### ISSUE THREAD

**Issue by zops** [tektoncd/triggers#306]
# body info:
`{
  "object_kind": "push",
  "event_name": "push",
 ...
  },
  "commits": [
    {
      "id": "e57b7098e944cbba6c153aeb9400cc89479dc783",
      "message": "20191227\n",
      "timestamp": "2019-12-27T06:58:57Z",
      "url": "http://xxx.com/xxx/knative-nodejs4/commit/e57b7098e944cbba6c153aeb9400cc89479dc783",
      "author": {
        "name": "xxx",
        "email": "xxx@xxx.com"
      },
      "added": [

      ],
      "modified": [
        "aws-node-serve-dynamic-html-via-http-endpoint/handler.js"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
  "push_options": [

  ],
  "repository": {
    "name": "knative-nodejs4",
    "url": "git@xxx:cc/knative-nodejs4.git",
    "description": "",
    "homepage": "http://xxxx/cc/knative-nodejs4",
    "git_http_url": "http://xxx/cc/knative-nodejs4.git",
    "git_ssh_url": "git@xxx:cc/knative-nodejs4.git",
    "visibility_level": 0
  }
}`

# Value（JSON）：
body.commits[0].id

# TriggerBinding 
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: my-pipeline-binding
  namespace: tekton-pipelines
spec:
  params:
  \- name: gitrevision
    value: $(body.commits[0].id)

-
-
-
- Does TriggerBinding support “body.commits[0].id”?

**Comment by dibyom** [comment]
I think this is due to the breaking change from GJSON to JSONPath for the triggerBinding syntax...most likely you are following the docs for the master version (using JSONPath) while the triggers installation is running the 0.1 release (using Gjson). Two options:
1. Follow the 0.1 docs: https://github.com/tektoncd/triggers/releases/tag/v0.1.0
OR 
2. Install the latest master version instead of the 0.1 release: https://github.com/tektoncd/triggers/blob/v0.1.0/DEVELOPMENT.md#install-triggers

**Comment by dibyom** [comment]
Closing this. Please re-open if the comment above did not solve this issue.
/close
