### ISSUE TITLE
Interceptor API: How to represent "OK, but don't continue"?

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#336]
Currently our API for interceptors treats a 200 OK status code as "request succeeded, continue", and treats any other response code as "there was an error, stop". We don't have a clear way to say "request succeeded, stop".

We should define a separate, Tekton specific way to describe this information.

# Option 1: Reuse HTTP response codes anyway

In this approach, we would say that `202 Accepted` means "message was received, do not continue".

While this would work, this feels a little bit like overloading the meanings of HTTP response codes. This is also makes it difficult to support other strategies that we may want to add later.

# Option 2: Custom HTTP Response header

When an interceptor request succeeds, but determines that the event should be filtered and trigger processing should be stopped, interceptors should return a header of the form:
```http
X-Tekton-Interceptor-Response: stop
```

This header instructs the EventListener on what to do when the response is returned. If no header is set we will assume it is equivalent to:
```http
X-Tekton-Interceptor-Response: success
```

This allows for minimal modification of the response body, but may make it harder to support non-HTTP transports that may not have a similar concept (e.g. gRPC) in the future.

This can be expanded to support other response strategies in the future, but we will also need to be careful about how to handle cases of the header having multiple values.

#  Option 3: HTTP Response Contract

In this approach, we enforce that Interceptors must return with a body of the form:
```json
{
  "status": "stop",
  "body": "..."
}
```

This response is a contract that must be fulfilled by all interceptors in order to be considered valid, where `body` is the value that will be forwarded on to the next interceptor.

This is probably the clearest mechanism for defining the API, but does mean that it becomes a bit more difficult to write pass-through interceptors (we will need to handle encoding/decoding response data into the `body` field).

---

Thoughts?

**Comment by vtereso** [comment]
Although we now have internal/core interceptors, I like to consider cases that use a network (similar to the recent [Round-Tripper update](https://github.com/tektoncd/triggers/commit/d182697ec591cbae1954deceaa663cd5aff7a814)) since it is unlikely we will satisfy everyone's use case out of the box. 

Currently, it seems like [we never return an HTTP failure code](https://github.com/tektoncd/triggers/blob/f7305fc38c962c4f68d03e54c757ba757284ce9f/pkg/sink/sink.go#L88) for the sink requests? Currently the [docs](https://github.com/tektoncd/triggers/blob/ba36f2b9f2c80421a8b4f6a3108173a9f4a5998a/docs/eventlisteners.md#event-interceptor-services) specify an interceptor should return HTTP 200 to continue, but it doesn't seem like these HTTP codes are used in the sink response? For simplicity, I would imagine any non 200 response from an interceptor would be routed to the sink response and the request should not continue. As a slight alternative, the sink could return some known code in such cases like `StatusBadRequest` or `StatusPreconditionFailed`. In this way, I think `Option 1` makes sense since ultimately the sink response HTTP response should in some way reflect the interceptor responses. I don't see any particular downsides (HTTP codes are robust) and it is also the most performant.

**Comment by bigkevmcd** [comment]
Maybe we extend the interceptor to be more explicit:

```
// Interceptor is the interface that all interceptors implement.
type Interceptor interface {
	ExecuteTrigger(req *http.Request) (*http.Response, bool, error)
}
```

The bool is true if it should continue, false if not, and that way the error can become less of a marker that the request should not continue?

**Comment by dibyom** [comment]
#271 is related

**Comment by dibyom** [comment]
This is possible now with #271 
/close
