### ISSUE TITLE
Handling Multiple Array values for JSONPath

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#338]
Say we have the following event body:
`{ body: [ {"a":"b"}, {"c","d"}, {"e":"f"} ] }`,

and a JSONPath expression in a TriggerBinding such as `$(body[0:2])`

# Expected Behavior

We should get a valid JSON array back e.g. `[ {"a": "b"}, {"c": "d"} ]` 

# Actual Behavior

Using JSONPath array accessors that return multiple elements (e.g. `$(body[0:2])`) returns each element separated by a space instead of a JSON array. In the example above, we get back:
`{"a": "b"} {"c": "d"}` 

# Additional Info
This is what `kubectl` does as well but I think that is ok behavior for a CLI, but for Triggers we should always return valid JSON

**Comment by vtereso** [comment]
It seems like we would need to change the [ported code from k8s.io/client-go/util/jsonpath/jsonpath.go](https://github.com/tektoncd/triggers/blob/b5944e5c66a04d4189376c2642d6657d80e022df/pkg/template/jsonpath.go#L62). The issue is still open/unresolved so uncertain if we should modify this ourselves or wait for it to be resolved.

**Comment by dibyom** [comment]
Yup! The workaround is a lot of work for the user. So, definitely worth fixing it.
