### ISSUE TITLE
Could not find the required trigger template or trigger bindings in namespace

### ISSUE THREAD

**Issue by JCzz** [tektoncd/triggers#349]
Creating Webhook

I am trying to create a webhook in the Tekton Dashboard.

I have successfully done:
build-docker-image-from-git-source:
https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs

And Triggers example:
https://github.com/tektoncd/triggers/tree/v0.1.0/examples

Now I am trying to create a github Webhook:
https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md

Then I get the following Error:
`Failed to create webhook, error returned was : Could not find the required trigger template or trigger bindings in namespace: tekton-pipelines. Expected to find: tutorial-pipeline-template, tutorial-pipeline-push-binding and tutorial-pipeline-pullrequest-binding`

From these Webhook Settings:

```
Name: tektonbuild-github-webhook
Repository URL: https://github.com/githubuser/tektonbuild.git
Access Token: xxxxx

Namespace: default
Pipeline: tutorial-pipeline
Service Account: tutorial-service
Docker Registry: gcr.io/<project>/imagetobuild
```

Question / problem:

1. 
From the error, I can read that Triggers has to be in the tekton-pipelines namespace with specific naming. But I don't understand this as the "Triggers example" works in the default namespace?

The error comes when I press the button "Create"

I can see in the documentation says " Pipeline definitions must be imported along with TriggerBindings and TriggerTemplates." Does that mean I have to "kubectl apply" TriggerBinding & TriggerTemplates , but not the PipelineRun, TaskRuns, Task and PipelineResources?

2.
In the dashboard When setting up Target pipeline:
I know I am just missing something, but why do we need to set the pipeline when creating a webhook and not the Eventlistener?

**Comment by ncskier** [comment]
Hi @JCzz, I'm going to copy this issue over to the [experimental](https://github.com/tektoncd/experimental) repository where the Webhooks Extension lives, and I'll answer your questions over there 🙂. It seems to me like the issue you're running into is due to how the Webhooks Extension is using Tekton Triggers; it isn't a problem with Tekton Triggers itself.

However, if I am mistaken, and/or you have any questions/comments specifically about the Tekton Triggers project, then please add those comments below.
