### ISSUE TITLE
Can the configuration automatically destroy the pod after the construction is completed?

### ISSUE THREAD

**Issue by lqy1992** [tektoncd/triggers#561]
# Expected Behavior
There is a configuration to automatically delete the pods generated by each pipeline
# Actual Behavior

# Steps to Reproduce the Problem

1. Pods are still on the list after running pipelines every time, it is not beautiful when there are more cicd tasks

# Additional Info

**Comment by ncskier** [comment]
If I understand correctly, you would like to clean up the Pods created from all of your PipelineRuns.

This sounds like an issue for the Pipelines repo rather than Triggers. Triggers is more concerned with creating resources (PipelineRuns & TaskRuns)... the lifecycle of these PipelineRuns & TaskRuns falls under the Pipelines project.

I did a quick search, and it looks like there is already an issue in the Pipelines repo about cleaning up PipelineRun Pods: https://github.com/tektoncd/pipeline/issues/2452. @lqy1992 can I close this issue, and you can follow up with https://github.com/tektoncd/pipeline/issues/2452?

**Comment by lqy1992** [comment]
ok,we hava same problem
