### ISSUE TITLE
Standardized TriggerBindings for Git providers in Catalog

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#584]
# Expected Behavior

We have a few standard bindings for Git providers (GitHub, GitLab, BitBucket) that all contain standardized param names (e.g. repo_clone_url, commit_id etc.). These standard bindings can be put in the Tekton Catalog (thanks @bobcatfish for the idea!).

# Actual Behavior
Users generally define their own TriggerBindings containing only the params they use.

# Additional Info
The goal for this issue is to see if this is feasible today, and what features are missing from Tekton that would prevent us from adding a feature like this.

/kind feature

**Comment by dibyom** [comment]
Discussion notes from May 26 WG:

TriggerBinding Catalog ideas - GitHub/GitLab/BitBucket Binding:
* All contain the same param names e.g. commit_id, repo_name, clone_url etc.
* [billy] Allow PipelineRuns to provide extra parameters · · tektoncd/pipeline#2513 probably a prereq
* [billy] Things like repo_name aren't always consistent - e.g. is repo name for * github.com/tektoncd/pipeline pipeline or tektoncd/pipeline?
* other common example: Clone URL (https, ssh, custom auth handler, etc)
* Kevin: working on this GitHub/GitLab
* add overlays to incoming payload with standard fields
* billy: generators for GitHub repo. Auto include GitHub bindings.
* How do we handle multiple/overrideable  bindings?

**Comment by bigkevmcd** [comment]
We could do something in the CEL/GitLab interceptors, and base it around exposing the hooks defined in https://github.com/jenkins-x/go-scm/blob/master/scm/webhook.go to bindings...

So, in a binding you could have `$(event.Repo.FullName)` etc.

This would have the benefit of using the same package we use for other things (go-scm), and reusing the standardisations inherent in that code.

**Comment by bigkevmcd** [comment]
We are building templated bindings, which can be reused, and modified.

**Comment by bigkevmcd** [comment]
What I'd propose for this:

1. Change the interface

```go
// Interceptor is the interface that all interceptors implement.
type Interceptor interface {
    ExecuteTrigger(req *http.Request) (context.Context, *http.Response, error)
}
```

The CEL and Webhook interceptors can return `request.Context()` i.e. pass the context through unchanged.

_Perhaps instead of modifying the body, the overlays could be added to a struct in the context by the CEL interceptor._

Change the GitHub and GitLab interceptors to use a GitHub or GitLab client and [Parse](https://godoc.org/github.com/jenkins-x/go-scm/scm#WebhookService) the incoming request.

This would have the side-effect of deprecating the `go-github` and custom secret comparison, as these can be delegated to go-scm.

Add the parsed [scm.Webhook](https://godoc.org/github.com/jenkins-x/go-scm/scm#Webhook) to the context.

Modify [sink.go](https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink.go#L189-L224) to pass in a context, and thread the context through each of the steps, and then return it.

Add logic in [sink.go](https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink.go#L143-L163) to extract the hook from the context, and pass it into [template.ResolveParams](https://github.com/tektoncd/triggers/blob/master/pkg/template/event.go#L30) which would call [applyEventValuesToParams](https://github.com/tektoncd/triggers/blob/master/pkg/template/event.go#L82) and have the hook (if one exists) added to the Event.

This would provide for template bindings like `$(hook.Ref)` which, for Push events, would yield something like `refs/heads/master`.

**Comment by bigkevmcd** [comment]
A quick stab at this (only supports GitHub for now, but it would be trivial to add GitLab) https://github.com/bigkevmcd/triggers/tree/git-intercepted-hooks

One of the issues is the discoverability of the fields in the `hook` inside the TriggerBindings, referring to a Go struct isn't particularly friendly, but the resources are complex.

The approach I linked at the end of the above proposal might be more appropriate (standardising further, and limiting the fields), or alternatively, perhaps a combination of both.

**Comment by dibyom** [comment]
Re-opening this. We discussed this for a bit but never really went anywhere. Would still like to explore some form of standardized bindings/catalog support
