### ISSUE TITLE
Proposal to rename TriggerBinding

### ISSUE THREAD

**Issue by EliZucker** [tektoncd/triggers#62]
If we're including conditionals and headermatching in `TriggerBinding`, then I would propose renaming it to something like `TriggerSifter` (open to alternatives).

I suggest this because the Trigger**Binding** name was created to reflect how it **binds** values from the event payload onto the `TrigerTemplate`, however it will now also be doing filtering and headermatching. I think the name should change to reflect the fact that more processing is done than just binding values.

**Comment by ncskier** [comment]
This is a good point, but I still don't mind the name `TriggerBinding` since we're binding event data to a set of output parameters (almost like a transformer). Plus there's conditional logic. So, I don't think it's _necessary_ to change the name, but if we find one that sounds better, I wouldn't be opposed to an update.

I don't really like `TriggerSifter` because I think it loses the idea of the `TriggerBinding` having output information. But in the same vein, maybe something like `TriggerRouter` or `EventRouter`?

Since we're trying to make the `TriggerBinding` more reusable, maybe we can use the word `Template` with something like `EventTemplate`?

**Comment by bobcatfish** [comment]
I feel like these days `TriggerBinding` really _only_ does binding, it no longer does anything conditional (I don't think?) since we moved that functionality into [interceptors](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#event-interceptors) so I think the name was good in the end and we could close this issue?
