### ISSUE TITLE
Triggers RBAC

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#68]
# Expected Behavior
Users should specify a service account (or a role binding?) in the `EventListener` to be used for resources created as per specific `TriggerTemplate`.

# Actual Behavior
Currently, there is no implementation.

# Additional Info
Currently, the `EventListener` creates a `Deployment` and a load balancer `Service` (to reference the deployment), which enables the pods to be addressable/receive external traffic. The service account tied to the `EventListener` listener pod has permissions necessary to read Triggers resources, but how can it get the permissions necessary for creating resources defined in a particular `TriggerTemplate`, which are arbitrary?

**Comment by vtereso** [comment]
We could simply add the permissions necessary to create Tekton resources as a default. If roles could be added onto a service account for the life of the `EventListener`, this might work well too.

**Comment by ncskier** [comment]
_Aside_: we currently don't have a good name for the pod/deployment that runs when an EventListener is created; I don't like calling the pod the EventListener, because that's already the name of the resource. For now, I'll call that pod/deployment the EventListener "sink."

---
So, the design challenge I see at the moment is that the EventListener "sink" pod needs to get/create two different sets of resources:
- get: Triggers resources (`EventListener`, `TriggerBinding`, and `TriggerTemplate`)
- create: Arbitrary resource types specified in the TriggerTemplate spec

The EventListener "sink" must be authorized by RBAC to handle both of these resource groups. I think that Triggers should probably handle configuring the "Triggers resources" authorization, and the user should have to configure the "Arbitrary resource types" authorization.

Please let me know if I'm missing something; is this way simpler than I'm making it out to be? Here are a couple of implementations that I have been thinking about to address this design challenge (feedback is very welcome, and sorry for the long comment 😅 ):

#### Idea 1: EventListener spec specifies a ServiceAccount
When creating an EventListener, the user specifies a ServiceAccount in the EventListener spec, and this ServiceAccount gets attached to the EventListener "sink," authorizing its k8s requests. The user must set up this ServiceAccount so that it has access to create all "Arbitrary resources" defined in the associated TriggerTemplates.

There will exist a ClusterRole called `event-listener-sink` (or something) which has access to get the "Triggers resources," and this ClusterRole will have been created [here](https://github.com/tektoncd/triggers/tree/master/config) when the user installed the TriggersProject. When the user creates an EventListener, our Triggers controller will create a ClusterRoleBinding to bind the `event-listener-sink` to the ServiceAccount specified in the EventListener spec. The EventListener resource will be one of the OwnerReferences on the ClusterRoleBinding, so when the EventListener is deleted, the ClusterRoleBinding will also be deleted.

✅ After the user has created their EventListener, the "sink" will be authorized by the user's ServiceAccount to create the "Arbitrary resource types specified in the TriggerTemplate spec," and the "sink" will be authorized by the `event-listener-sink` ClusterRole attached to the user's ServiceAccount to get "Triggers resources."

#### Idea 2: TriggerTemplate spec specifies a Role
This idea is motivated by the notion that since the TriggerTemplate defines the resources that it creates, it makes sense that it would also specify the authorization mechanism to create these resources.

When creating a TriggerTemplate, the user specifies a Role (or ClusterRole?) in the TriggerTemplate spec, which has authorization to create the "Arbitrary resource types specified in the TriggerTemplate."

There will exist the `event-listener-sink` ClusterRole from __Idea 1__ which has access to get the "Triggers resources." When an EventListener is created, the Triggers controller will create:
- a ServiceAccount
- the Role specified in the TriggerTemplate
- a RoleBinding that attaches this Role to the ServiceAccount
- a ClusterRoleBinding attaching the `event-listener-sink` ClusterRole to the ServiceAccount

Similarly to __Idea 1__, the ServiceAccount, Role, RoleBinding, and ClusterRoleBinding would all have the EventListener as one of their OwnerReferences. So, when the EventListener is deleted, all of these generated resources will also be deleted.

✅ After the user has created their EventListener, the "sink" will be authorized by the TriggerTemplate's Role bound to the generated ServiceAccount to create the "Arbitrary resource types specified in the TriggerTemplate spec," and the "sink" will be authorized by the `event-listener-sink` ClusterRole bound to the generated ServiceAccount to get "Triggers resources."

**Comment by vtereso** [comment]
Idea one 🙏

**Comment by vincent-pli** [comment]
Could we add permission for all resource of group `tekton.dev` (Pipeline) to `ClusterRole`: `event-listener-sink`.
I think most of case are in the scope of `tekton pipeline`.

Base on that, I'm a little prefer idea two. With idea two, 
- In most of case (in tekton-pipeline), use need do nothing more than create `EventListener`, `TriggerBinding` and `TriggerTemplate`.
- If user want to handle resource not in `tekton-pipeline`, they should define `resource` in `TriggerTemplate` and of course should define the `role` in same place.

**Comment by iancoffey** [comment]
Another vote for idea #1 👍

**Comment by vtereso** [comment]
Creating service accounts automatically seem questionable. Adding access to the Triggers resources shouldn't be an issue. I will take this approach.
/assign

**Comment by ncskier** [comment]
So that we only give access to read the Triggers resources in the current namespace, we can create a `Role` in that namespace with only `get` 👍

**Comment by bobcatfish** [comment]
@vtereso if we agree that it isn't necessary, what do you think about moving this out of the 0.1 milestone and revisiting it later?

Alternatively I could settle for making it configurable and off by default like you said, but my preference is (always XD) to avoid adding functionality as long as we can until we're sure we need it.

**Comment by vtereso** [comment]
I think it removing it from the milestone makes sense.

**Comment by bobcatfish** [comment]
kk sounds good - thanks @vtereso !

**Comment by vtereso** [comment]
As per WG, this doesn't seem necessary so I am closing.
