### ISSUE TITLE
failed calling webhook x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Hokwang** [tektoncd/triggers#875]
Hi,

I have on-prem kubernetes cluster.

I installed pipeline, dashboard, triggers.
And following getting-started,
when I run below command, there's error.

```
$ kubectl apply -f ./docs/getting-started/triggers.yaml
Error from server (InternalError): error when creating "./docs/getting-started/triggers.yaml": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post https://tekton-triggers-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s: x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "./docs/getting-started/triggers.yaml": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post https://tekton-triggers-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s: x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "./docs/getting-started/triggers.yaml": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post https://tekton-triggers-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s: x509: certificate signed by unknown authority
```

I don't know why this error occurs.

# Additional Info
- Kubernetes version: 1.17.11
- Tekton Pipeline version: 0.19.0

**Comment by dibyom** [comment]
I wonder if this has something to do with the on prem k8s setup. I think what's happening is that the K8s API server is sending a request to the Triggers webhook but its failing due to the self signed certs.

Does this also happen when creating pipeline resources?
Is there anything in the webhook logs? (`kubectl -n tekton-pipelines logs -f  tekton-triggers-webhook-xxx`)

**Comment by Hokwang** [comment]
@dibyom 
Yes, my kubernetes cluster is on on-prem and installed using kubeadm.

Actually tekton pipeline has same problem. (https://github.com/tektoncd/pipeline/issues/3609)

In this case, I removed
`mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.pipeline.tekton.dev` and
`validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.pipeline.tekton.dev`.
and then it works.
But I want to find out real problem and radical solution.

Here's my log.
```
$ kubectl -n tekton-pipelines logs tekton-triggers-webhook-5cff7bb6fd-whp6r
<snip>
{"level":"info","ts":"2020-12-22T02:52:38.423Z","logger":"webhook-triggers.ValidationWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 108.760025ms","knative.dev/traceid":"0baa7fe5-b942-4bec-9d42-427684a20132","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"error","ts":"2020-12-22T02:52:38.423Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:528","msg":"Reconcile error","error":"failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"config.webhook.triggers.tekton.dev\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:528\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:514\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:451"}
{"level":"info","ts":"2020-12-22T02:52:38.424Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:515","msg":"Reconcile failed. Time taken: 109.096373ms","knative.dev/traceid":"667c8f47-911e-4beb-9610-f43cf7e5eecb","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.424Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 52.926014ms","knative.dev/traceid":"b5c46d55-3c3d-4452-9dd7-05b88cf03bcd","knative.dev/key":"config.webhook.triggers.tekton.dev"}
{"level":"error","ts":"2020-12-22T02:52:38.424Z","logger":"webhook-triggers.DefaultingWebhook","caller":"controller/controller.go:528","msg":"Reconcile error","error":"failed to update webhook: Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io \"webhook.triggers.tekton.dev\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:528\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:514\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20200922164940-4bf40ad82aab/controller/controller.go:451"}
{"level":"info","ts":"2020-12-22T02:52:38.424Z","logger":"webhook-triggers.DefaultingWebhook","caller":"controller/controller.go:515","msg":"Reconcile failed. Time taken: 109.26973ms","knative.dev/traceid":"e27c8fc7-3ff2-4436-827d-d72482eecf14","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.425Z","logger":"webhook-triggers.DefaultingWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 52.906086ms","knative.dev/traceid":"f00ffd19-4ca6-4bb1-8922-516a6e48ced7","knative.dev/key":"webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.426Z","logger":"webhook-triggers.ValidationWebhook","caller":"validation/reconcile_config.go:169","msg":"Updating webhook","knative.dev/traceid":"f1ac589d-11f1-4c1b-a359-85672f7a638d","knative.dev/key":"validation.webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.428Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"configmaps/configmaps.go:165","msg":"Webhook is valid","knative.dev/traceid":"2168ebfd-9b85-49c5-bdcf-9a579b381f60","knative.dev/key":"config.webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.428Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 3.602086ms","knative.dev/traceid":"2168ebfd-9b85-49c5-bdcf-9a579b381f60","knative.dev/key":"config.webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.429Z","logger":"webhook-triggers.DefaultingWebhook","caller":"defaulting/defaulting.go:206","msg":"Updating webhook","knative.dev/traceid":"91835c99-0add-469b-bad6-13eebdc3d912","knative.dev/key":"webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.429Z","logger":"webhook-triggers.ValidationWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 7.408414ms","knative.dev/traceid":"f1ac589d-11f1-4c1b-a359-85672f7a638d","knative.dev/key":"validation.webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.431Z","logger":"webhook-triggers.DefaultingWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 6.636123ms","knative.dev/traceid":"91835c99-0add-469b-bad6-13eebdc3d912","knative.dev/key":"webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.432Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"configmaps/configmaps.go:165","msg":"Webhook is valid","knative.dev/traceid":"9da192b0-da66-44e5-ad48-c29b3228a8e3","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.432Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 3.605146ms","knative.dev/traceid":"9da192b0-da66-44e5-ad48-c29b3228a8e3","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.433Z","logger":"webhook-triggers.DefaultingWebhook","caller":"defaulting/defaulting.go:206","msg":"Updating webhook","knative.dev/traceid":"2f4db1df-3b0f-4f54-a451-90c83a55e452","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.438Z","logger":"webhook-triggers.DefaultingWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 9.134619ms","knative.dev/traceid":"2f4db1df-3b0f-4f54-a451-90c83a55e452","knative.dev/key":"tekton-pipelines/triggers-webhook-certs"}
{"level":"info","ts":"2020-12-22T02:52:38.746Z","logger":"webhook-triggers.ValidationWebhook","caller":"validation/reconcile_config.go:169","msg":"Updating webhook","knative.dev/traceid":"b74303bf-ef2f-4be7-a26c-3214ad82ba12","knative.dev/key":"validation.webhook.triggers.tekton.dev"}
{"level":"info","ts":"2020-12-22T02:52:38.749Z","logger":"webhook-triggers.ValidationWebhook","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 7.141622ms","knative.dev/traceid":"b74303bf-ef2f-4be7-a26c-3214ad82ba12","knative.dev/key":"validation.webhook.triggers.tekton.dev"}
```

**Comment by dibyom** [comment]
> In this case, I removed
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.pipeline.tekton.dev and
validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.pipeline.tekton.dev.
and then it works.

Yes, that would work since it removes the webhooks but that way you won't get any of the benefits from the webhooks (validation + setting default values etc.)


The way the certs work for webhooks (for both pipelines and triggers)  is : 

1. We install the [webhook server deployment](https://github.com/tektoncd/triggers/blob/master/config/webhook.yaml) + the [webhook config](https://github.com/tektoncd/triggers/blob/master/config/500-webhooks.yaml)

2. The webhook deployment includes a certificates controller that will look for a [pre-defined secret](https://github.com/tektoncd/triggers/blob/master/config/webhook.yaml#L66-L67). This certificate controller is responsible for [creating the certs if it does not exist, or rotating them regularly](https://github.com/tektoncd/triggers/blob/master/vendor/knative.dev/pkg/webhook/certificates/certificates.go#L62). 

3. Each webhook  also keeps a watch on the above secret and updates it configuration to add/modify the `caBundle` field when the secret changes ([example](vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
))


My guess is that there is something going wrong in the above process. I'd look into the secret to see if it was being populated correctly. If it is, then I'd look into the actual webhook configurations to see if the webhook deployment has updated the `clientConfig.caBundle` field with the above secret. If they fail, there should be an error log in the webhook logs (probably towards the beginning of the log since this should happen as soon as the webhook is deployed)

**Comment by Hokwang** [comment]
I fix this problem.
In /etc/kubernetes/manifests/kube-apiserver.yaml, there's no_proxy setting.
but there's no `.svc`.

I added it and now works perfectly.

**Comment by anilkumarpanditi** [comment]
Hi,
We are facing the same issue on Openshift 4.7 , could you please tell the steps to add  .svc.

**Comment by shinuza** [comment]
Here's how I fixed it since I didn't have access to the kubernetes nodes, in my case this is cause by the fact that the root CA in 

`kubectl get configmaps -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}'`

Was modified by the team that installed the cluster. So the issuer, was not `kubernetes` but `my-company`. If you look at the `webhook-certs` and `triggers-webhook-certs` secrets you will see that they have 3 fields.

- server-cert.pem
- server-key.pem
- ca-cert.pem

The `ca-cert.pem` value needs to be injected in the `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration`, see [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly) for more information.

1. Create the configmaps before creating the deployments for pipeline, those deployments expect the configmaps to exist, otherwise they won't start
2. Create the deployments and wait for them to start
3. Get the value of the `webhook-certs` will be populated 
4. Get the ca-cert.pem content `kubectl -n tekton-pipelines get secret webhook-certs -o jsonpath='{.data.ca-cert\.pem}' and add the `caBundle` key with this value.
5. From there you can finish the installation as normal (triggers, interceptors, etc...)

**Comment by antoniosthanasisgit** [comment]
Try to change cert-manager version to v1.4.0 it works for me 
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.yaml

**Comment by graham924** [comment]
I also encountered this problem and the solution was to remove the problematic webhook, trigger the reconstruction of the Tekton pipeline, and inject it with the latest caBundle from secret.
I compared the Cabundle of the old webhook with the new and found that it was different. So my guess is that the Environment's legacy webhook certificates haven't expired at deployment, so they won't trigger an update of the webhook certificates, which are in fact untrusted and need to be replaced
