### ISSUE TITLE
EventListener sometimes fails to resolve binding

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/triggers#896]
Hi,

for our tekton deployment, sometimes we see EventListeners failing to process events with the following information in the log

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:225","msg":"failed to resolve bindings: error getting TriggerBinding : triggerbinding.triggers.tekton.dev \"visit-management-system-vmsbackend-pr\" not found","knative.dev/controller":"eventlistener","/triggers-eventid":"pprlz","/trigger":"visit-management-system-vmsbackend-pr","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:225\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:129"}
```

The mentioned TriggerBinding however exists. Do you have an idea why this fails sometimes? Is there anything i can check?

Thanks, Fabian

EventListener
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: "2020-12-21T15:43:58Z"
  finalizers:
  - eventlisteners.triggers.tekton.dev
  generation: 1
  labels:
    beekeeper/scope: Namespace
  name: visit-management-system-vmsbackend
  namespace: site-itscb
  ownerReferences:
  - apiVersion: beekeeper.sap.it/v1alpha1
    kind: NeoJavaApplication
    name: visit-management-system-vmsbackend
    uid: e5d1c689-4531-482e-8d32-a783e0def219
  resourceVersion: "438851105"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/site-itscb/eventlisteners/visit-management-system-vmsbackend
  uid: 542a307f-b1cb-48e8-8173-09498e073441
spec:
  podTemplate: {}
  resources: {}
  serviceAccountName: tekton-triggers-listener
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: visit-management-system-vmsbackend-ci-master
    interceptors:
    - cel:
        filter: body.ref == 'refs/heads/master'
    name: visit-management-system-vmsbackend-ci-master
    template:
      name: visit-management-system-vmsbackend-ci-master
  - bindings:
    - kind: TriggerBinding
      ref: visit-management-system-vmsbackend-pr
    interceptors:
    - cel:
        filter: body.ref != 'refs/heads/master'
    name: visit-management-system-vmsbackend-pr
    template:
      name: visit-management-system-vmsbackend-pr
status:
  address:
    url: http://el-visit-management-system-vmsbackend.site-itscb.svc.cluster.local:8080
  conditions:
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Deployment exists
    status: "True"
    type: Deployment
  - lastTransitionTime: "2021-01-07T17:12:03Z"
    message: ReplicaSet "el-visit-management-system-vmsbackend-c57b9949b" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-01-13T11:05:21Z"
    message: Service exists
    status: "True"
    type: Service
  configuration:
    generatedName: el-visit-management-system-vmsbackend
```

TriggerBinding
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: "2020-12-21T15:57:59Z"
  generation: 1
  labels:
    beekeeper/scope: NeoJavaApplication-visit-management-system-vmsbackend
  name: visit-management-system-vmsbackend-pr
  namespace: site-itscb
  ownerReferences:
  - apiVersion: beekeeper.sap.it/v1alpha1
    kind: NeoJavaApplication
    name: visit-management-system-vmsbackend
    uid: e5d1c689-4531-482e-8d32-a783e0def219
  resourceVersion: "350591728"
  selfLink: /apis/triggers.tekton.dev/v1alpha1/namespaces/site-itscb/triggerbindings/visit-management-system-vmsbackend-pr
  uid: 8d13d32b-9c9b-4833-83c1-b9fd9b65bb24
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
```

# Additional Info

- Kubernetes version: `v1.18.12`
- Tekton Pipeline version: `v0.19.0`
- Tekton Triggers version: `v0.10.2`

**Comment by dibyom** [comment]
> Tekton Triggers version: v0.10.2

Looks like you are running a fairly old version of Triggers...in that release we'd make a call to the API server directly each time we wanted to resolve a binding. In newer releases, we use a lister so that the result is cached and we do not have to make a network call (reducing the chances of failure). Also in newer releases, you have the ability to inline/embed the binding within your Trigger spec.

I think both of these should help. Does this problem also occur in a more recent version of Triggers?

**Comment by Fabian-K** [comment]
Thanks for the quick reply! I´m confused... isnt 0.10.2 the latest version of triggers?

**Comment by dibyom** [comment]
> Thanks for the quick reply! I´m confused... isnt 0.10.2 the latest version of triggers?

You are absolutely correct. I'm going to blame a lack of coffee 🤦 

(I think using embedded bindings should still work as a workaround).

One question: Does this happen when you initially create a Trigger/EventListener/Binding? Or does this consistently happen even when an EL has been running for some time?

**Comment by Fabian-K** [comment]
Hehe, happens to me all the time :D

The log message was from today, the trigger, and the event listener was created last year. I do not know for how long the pod of the event listener existed tough.

Embedding sounds like a good idea, I ´ll definitely try this

**Comment by Fabian-K** [comment]
We now embed the TriggerBinding into the EventListener. Unfortunately we can´t do this (yet) for the TriggerTemplate as the model of our client needs to be updated first, so we now face some `error getting TriggerTemplate ...`. So far I´m only seeing this issue on event listener pods that got restarted, I´m wondering if that is a coincidence... 🙇‍♂️

**Comment by dibyom** [comment]
so when the pods get restarted, you get the error message for a while and then everything works? Or is the error continuous?

**Comment by Fabian-K** [comment]
Somehow I have the feeling that once a EventListener pod shows the error, all future events handled by the pod will also fail. Unfortunately only a feeling, I´ll have to observe this better

**Comment by elixirl1l** [comment]
I have to rollback to v0.9.1 due to this issue.

**Comment by mjgallag** [comment]
I believe I just had this issue. Here is log before restart:
```
{"level":"info","ts":"2021-02-25T23:02:18.072Z","logger":"eventlistener","caller":"resources/create.go:103","msg":"For event ID \"z2mtq\" creating resource tekton.dev/v1beta1, Resource=pipelineruns","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/resources/create.go","line":"103","function":"github.com/tektoncd/triggers/pkg/resources.Create"}}
```
Here is log after restart:
```
{"level":"info","ts":"2021-02-25T23:03:24.716Z","caller":"logging/config.go:115","msg":"Successfully created the logger.","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"115","function":"knative.dev/pkg/logging.newLoggerFromConfig"}}
{"level":"info","ts":"2021-02-25T23:03:24.716Z","caller":"logging/config.go:116","msg":"Logging level set to: info","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"116","function":"knative.dev/pkg/logging.newLoggerFromConfig"}}
{"level":"info","ts":"2021-02-25T23:03:24.716Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/pkg@v0.0.0-20210107022335-51c72e24c179/logging/config.go","line":"78","function":"knative.dev/pkg/logging.enrichLoggerWithCommitID"}}
{"level":"info","ts":"2021-02-25T23:03:24.716Z","logger":"eventlistener","caller":"logging/logging.go:47","msg":"Starting the Configuration eventlistener","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/logging/logging.go","line":"47","function":"github.com/tektoncd/triggers/pkg/logging.ConfigureLogging"}}
{"level":"info","ts":"2021-02-25T23:03:24.829Z","logger":"eventlistener","caller":"eventlistenersink/main.go:76","msg":"EventListener pod started","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/cmd/eventlistenersink/main.go","line":"76","function":"main.main"}}
{"level":"info","ts":"2021-02-25T23:03:24.847Z","logger":"eventlistener","caller":"eventlistenersink/main.go:119","msg":"Listen and serve on port 8000","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/cmd/eventlistenersink/main.go","line":"119","function":"main.main"}}
{"level":"error","ts":"2021-02-25T23:39:52.625Z","logger":"eventlistener","caller":"sink/sink.go:80","msg":"Error getting EventListener git-webhook in Namespace dev-hello-world: eventlistener.triggers.tekton.dev \"git-webhook\" not found","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"80","function":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent"},"stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:80\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2417\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\tnet/http/server.go:3272"}
```

Unfortunately, I didn't figure out why it restarted. I tried scaling deployment to 0 and then back up to 1, triggering another restart and it still couldn't find `EventListener` even though it was there. I deleted and recreated `EventListener` and it started working again.

I realize now that this has happened to me a least a few times in the past over the last few months.

Suggestions for what data I should collect the next time it happens that may help to root cause?

**Comment by dibyom** [comment]
https://github.com/tektoncd/triggers/pull/977 should help here I think (we are forcing the EL to fetch the spec before starting to process any triggers). 
That being said, I've started noticing this in our e2e tests quite a bit (they fail due to the bindings failing to be found)

I think this has something to do with the lister that we use to fetch these resources using stale data but I'm not 100% sure. One way forwards that @jmcshane suggested was to resolve all Triggers an EL will process at EL startup.

**Comment by dibyom** [comment]
Did some digging today. I think I know what's going on here:

1. First, we create a [sharedInformerFactory](https://github.com/tektoncd/triggers/blob/02c38968e98d2d428498c0ffccfed4645e2fcf7f/cmd/eventlistenersink/main.go#L89-L94)

2. Next, in a separate goroutine, we call [`factory.Start()`](https://github.com/tektoncd/triggers/blob/02c38968e98d2d428498c0ffccfed4645e2fcf7f/cmd/eventlistenersink/main.go#L96-L99).  Notably at this point, the factory does not have any informers/listers registered since we make the calls to use them in the following step

3.  Next, we actually [make calls to Listers() for the various types](https://github.com/tektoncd/triggers/blob/02c38968e98d2d428498c0ffccfed4645e2fcf7f/cmd/eventlistenersink/main.go#L112-L117). This is the essential part - when we first [make the call to Lister(), it calls Informer()](https://github.com/tektoncd/triggers/blob/02c38968e98d2d428498c0ffccfed4645e2fcf7f/pkg/client/informers/externalversions/triggers/v1alpha1/trigger.go#L89) which then adds [the Informer type to the list of informer types that the factory cares about](https://github.com/tektoncd/triggers/blob/02c38968e98d2d428498c0ffccfed4645e2fcf7f/pkg/client/informers/externalversions/factory.go#L147-L165).

The issue is that I think we want 2. to happen after 3. And in addition., there is a WaitForCacheSync method on the factory that we should call so that we sync the cache before serving traffic (@jmcshane did this manually for the EventListener type, but this method should do it for all informers).

**Comment by jmcshane** [comment]
@dibyom awesome digging. this makes a ton of sense. if you implement 2, i would also remove the hack that fails when the el resolution fails

**Comment by dibyom** [comment]
https://github.com/tektoncd/triggers/pull/1012 is where I have been playing around with this.

**Comment by Fabian-K** [comment]
Great to see this, thank you!

**Comment by badamowicz** [comment]
Hi all!
We've upgraded to Triggers v0.13.0 several days ago and still are facing this issue.
`{"level":"error","ts":"2021-05-21T10:26:55.905Z","logger":"eventlistener","caller":"sink/sink.go:223","msg":"failed to resolve bindings: error getting TriggerBinding : triggerbinding.triggers.tekton.dev \"cd-deploy-binding\" not found","knative.dev/controller":"eventlistener","/triggers-eventid":"e091d12a-c496-4d1e-a4b3-5892083ad7ca","/trigger":"cd-deploy-trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:223\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:127"}`
Seems ist happens even more often as it did before v0.13.0. So looks like a regression for me.
Just wanted to let you know. Let me know if I can provide further information.
