### ISSUE TITLE
EventListener and Trigger relation clarification

### ISSUE THREAD

**Issue by goldmann** [tektoncd/triggers#996]
I would like to understand why we declare/reference Triggers in EventListeners and not the other way around - in Triggers we reference EventListeners?

In order to create a new Trigger in the system I need to update the EventListener so it starts to work. I would imagine that I could create a Trigger with a reference to particular EventListener instead. This would be picked up by the controller and EventListener configuration would be updated. This would free from updating the EventListener configuration and would be generally speaking preferable.

Am I missing something obvious here?

**Comment by goldmann** [comment]
Let me explain my assumptions and my use case here for better understanding.

My system works on top of Triggers and Tekton in general. Usage of this system is partitioned by namespace. Each "user" gets a new namespace in the cluster.

All Triggers and are created (and managed in generally) automatically by the system. This means that where there is a need for new Trigger it is created. When it's no longer necessary - it is removed.

I use Knative Eventing and use Knative Triggers to send messages of particular type to particular Tekton Triggers EventListener. I'm bundling events by the event type so a particular Tekton EventListener receives a singe event type. I have as many EventListeners as event types I want to handle.

I have only two TriggerTemplates, about 10 event types to cover. There are multiple TriggerBindings as well (basically a matrix of event type and template).

Some questions:

1. Does above make sense?
2. Is there a better way to do it?
3. Am I misusing some Trigger concepts?
4. What is the best practice around EventListeners? Event types, number of EL, cluster-wide vs. namespaced.

**Comment by dibyom** [comment]
Hi @goldmann great questions :)

You are right that initially the model was that users would have to directly reference triggers in the EventListener. However, with [TEP-009](https://github.com/tektoncd/community/blob/main/teps/0009-trigger-crd.md) we added namespace selectors which allows an EventListener to select all Triggers within a specified namespace without then having to be explicitly specified in the EL spec. We are also close to landing a [similar label based selector mechanism](https://github.com/tektoncd/triggers/pull/970) that will allow an EL to select a subset of triggers based on labels. 

Some context for the design and alternatives is in this [design doc](https://docs.google.com/document/d/1zWpmEhtSNe8KAPKvTJE7Pjg5Uzk8mx9MUjSN24D1jUg/edit#heading=h.emfu2q8r4dx8) (you'lll have to join the tekton-dev mailing list to view).  


That being said, most of our examples still use the old way of directly referencing a Trigger from within an EL's namespace which gives the impression that it is the best practice. We definitely need to update those.

To answer your questions:

> 1. Does above make sense?

Yup, your use case makes perfect sense!

> 2. Is there a better way to do it?

I think your approach is fine. I'm wondering why you chose one event type per EL though? There is nothing wrong with that, just curious! (One alternative could be to use one EL but with separate CEL filters for each event type?)

> 3. Am I misusing some Trigger concepts?

I don't think so 😄  Are you 

> 4. What is the best practice around EventListeners? Event types, number of EL, cluster-wide vs. namespaced.

I think this depends on your use case -- how are you managing the ELs? Will having many ELs make it harder to manage? You could have one cluster wide EL but that EL will have to use a service account that has access to create taskruns/pipelineruns across multiple namespaces...is that fine for your use cases? Otherwise, you might need to have an EL per namespace.
